// <auto-generated />
using System;
using GeoAI.UrbanTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoAI.UrbanTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoAI.UrbanTracker.Api.Models.AnalysisRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnalysisRequests");
                });

            modelBuilder.Entity("GeoAI.UrbanTracker.Api.Models.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRequestId")
                        .HasColumnType("uuid");

                    b.Property<double>("BuiltUpAreaChangePercent")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeminiSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GreenAreaChangePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("NdviAfter")
                        .HasColumnType("double precision");

                    b.Property<double>("NdviBefore")
                        .HasColumnType("double precision");

                    b.Property<double>("NdviChangePercent")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRequestId")
                        .IsUnique();

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("GeoAI.UrbanTracker.Api.Models.SatelliteImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CaptureDate")
                        .HasColumnType("date");

                    b.Property<double>("CloudCoveragePercent")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBeforeImage")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRequestId");

                    b.ToTable("SatelliteImages");
                });

            modelBuilder.Entity("GeoAI.UrbanTracker.Api.Models.AnalysisResult", b =>
                {
                    b.HasOne("GeoAI.UrbanTracker.Api.Models.AnalysisRequest", "AnalysisRequest")
                        .WithOne("Result")
                        .HasForeignKey("GeoAI.UrbanTracker.Api.Models.AnalysisResult", "AnalysisRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRequest");
                });

            modelBuilder.Entity("GeoAI.UrbanTracker.Api.Models.SatelliteImage", b =>
                {
                    b.HasOne("GeoAI.UrbanTracker.Api.Models.AnalysisRequest", "AnalysisRequest")
                        .WithMany("SatelliteImages")
                        .HasForeignKey("AnalysisRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRequest");
                });

            modelBuilder.Entity("GeoAI.UrbanTracker.Api.Models.AnalysisRequest", b =>
                {
                    b.Navigation("Result");

                    b.Navigation("SatelliteImages");
                });
#pragma warning restore 612, 618
        }
    }
}
